### ISSUE TITLE
Error switching night mode to another mode

### ISSUE THREAD

**Issue by Delaballe85** [Robbe-B/maestro_mcz#107]
**Describe the bug**
When we are in night mode and we want to switch to another mode (example auto mode) I get the following error:

Failed to call the climate/set_preset_mode service. integer division or modulo by zero

Even if the heating is turned off, the error can be reproduced.

**Comment by Robbe-B** [comment]
@Delaballe85,

Thanks for reporting this issue. 
Can please provide me with the diagnostics file of the integration ? 
Only with that I'll be able to see what the issue is here.

Kind regards,
Robbe

**Comment by Delaballe85** [comment]
@Robbe-B 

Hello,

To begin with, thank you very much for your work and the speed with which you provide answers. You will find attached the diagnostic file, hoping that it is the correct file.

[config_entry-maestro_mcz-22005128f51bf488c44e8e0b1740b35d.json](https://github.com/Robbe-B/maestro_mcz/files/14301180/config_entry-maestro_mcz-22005128f51bf488c44e8e0b1740b35d.json)

I also add the log history below.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:240
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 15:58:00 (4 occurrences)
Last logged: 19:52:31

[139909439704000] integer division or modulo by zero
[139908793966912] integer division or modulo by zero
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 709, in async_handle_set_preset_mode_service
    await self.async_set_preset_mode(preset_mode)
  File "/config/custom_components/maestro_mcz/climate.py", line 146, in async_set_preset_mode
    await self.coordinator.update_data_after_set()
  File "/config/custom_components/maestro_mcz/__init__.py", line 117, in update_data_after_set
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 289, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 412, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 183, in async_update_listeners
    update_callback()
  File "/config/custom_components/maestro_mcz/fan.py", line 190, in _handle_coordinator_update
    self.handle_coordinator_update_internal()
  File "/config/custom_components/maestro_mcz/fan.py", line 253, in handle_coordinator_update_internal
    self._attr_percentage = ranged_value_to_percentage((1, self._attr_speed_count),fan_value)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/percentage.py", line 79, in ranged_value_to_percentage
    return scale_ranged_value_to_int_range(low_high_range, (1, 100), value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/scaling.py", line 23, in scale_ranged_value_to_int_range
    (value - source_offset)
ZeroDivisionError: integer division or modulo by zero
```

Thank you again and if you need any other information, don't hesitate.
