### ISSUE TITLE
Integration fails

### ISSUE THREAD

**Issue by xvisionbelgium** [Robbe-B/maestro_mcz#155]
Since sat sept 14 the mcz integration starts failing.
The following error is logged

This error originated from a custom integration.

Logger: custom_components.maestro_mcz.config_flow
Source: custom_components/maestro_mcz/config_flow.py:63
integration: Maestro MCZ (documentation, issues)
First occurred: September 14, 2024 at 11:41:24 PM (1 occurrences)
Last logged: September 14, 2024 at 11:41:24 PM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/maestro_mcz/maestro/controller/maestro_controller.py", line 45, in MakeRequest
    async with session.get(url, headers=headers) as resp:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1353, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 684, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 999, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/maestro_mcz/config_flow.py", line 63, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/maestro_mcz/config_flow.py", line 41, in validate_input
    await controller.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/controller/maestro_controller.py", line 98, in StoveInfo
    await maesto_stove.AsyncInit()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 27, in AsyncInit
    self._model = await self.StoveModel()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in StoveModel
    await self._controller.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/controller/maestro_controller.py", line 39, in MakeRequest
    async with async_timeout.timeout(15):
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

**Comment by Robbe-B** [comment]
@xvisionbelgium,

This might be related to the MCZ cloud being down at that time.

Can you try to reload the integration and check everything works again ?

Kind regards,
Robbe

**Comment by Robbe-B** [comment]
@xvisionbelgium, 
Any update on this ?

**Comment by Robbe-B** [comment]
@xvisionbelgium, 
It's indeed the MCZ backend that sometimes goes down.
I'll close this issue since it's not something we can fix in the integration.
If you like the work we do, don't forget to give this repo a star !
Kind regards,
Robbe
