### ISSUE TITLE
Solving blocking I/O in the event loop

### ISSUE THREAD

**Issue by Robbe-B** [Robbe-B/maestro_mcz#166]
Beginning in version 2024.7.0, Home Assistant can detect more blocking operations in the event loop to prevent system instability.
It detects blocking event loop things for this integration a well, it's related to the way we read in mocked files for debugging: 

`2024-12-11 08:11:01.776 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to listdir with args ('config/custom_components/maestro_mcz/mocked',) inside the event loop by custom integration 'maestro_mcz' at custom_components/maestro_mcz/__init__.py, line 83: files_in_dir = os.listdir(folder_path) (offender: /config/custom_components/maestro_mcz/__init__.py, line 83: files_in_dir = os.listdir(folder_path)), please create a bug report at https://github.com/Robbe-B/maestro_mcz/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 788, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
    await self.__async_setup_with_context(hass, integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/maestro_mcz/__init__.py", line 41, in async_setup_entry
    mocked_files = has_mocked_files()
  File "/config/custom_components/maestro_mcz/__init__.py", line 83, in has_mocked_files
    files_in_dir = os.listdir(folder_path)
`

**Comment by mottobug** [comment]
Hi, is there a solution for that? I see exactly this problem in the log and the integration does not work properly anymore. It changes state every few seconds.

**Comment by mottobug** [comment]
Nevermind, i think my oven is going nuts. I don't think it has to do anything with the integration.

**Comment by Robbe-B** [comment]
@mottobug,

It has nothing todo with this intgration.
I think the MCZ Cloud is messed up again.
Because I see the same behavior here.
Kind regards,
Robbe

**Comment by mottobug** [comment]
Yeah, these people on the MCZ cloud are not exactly what i call "experts". Now my oven wan't even start manually. Jeeez. What a mess.

**Comment by Robbe-B** [comment]
@mottobug,
It's indeed not very professional. 
Sadly for us, because there prices are very professional...
All we can do is make integrations like this to kinda handle a lot of inconsistencies across there systems. 
But like we mentioned before, there is no official API from MCZ so we are always 1 step behind.

If you like the work we do, consider leaving a star ⭐ on this repository.
Kind Regards,
Robbe
